spring:
    profiles:
         active: standalone
#        active: deployed
    main:
        show_banner: false

    view:
        prefix: /WEB-INF/views/
        suffix: .jsp

logging:
    level:
        com.culqi: DEBUG
        #org.springframework: WARN
        #org.apache: WARN

jsse:
    enableSNIExtension: false

