server:
    port: 8003

logging:
    level:
        com.culqi: DEBUG
        # org.springframework: WARN
        # org.springframework.web.client: DEBUG

culqi:
    url:
        mod_pago: http://192.168.1.91:8001
        mod_pago_integ: http://192.168.1.91:8001/api/v1/suscripciones
        mod_pago_cargos: http://192.168.1.91:8001/api/v1/cargos
        mod_suscripciones: http://localhost:8001/ejemplo-suscripcion
    config:
        codigoComercio: DJrWAvdN9NB2
        llaveSecreta: 5LIwaCW2C+57sfp+68b24zZ6vJCESSrXneZLye5pJZs=