server:
    port: 8001

logging:
    level:
        com.culqi: DEBUG
        # org.springframework: WARN
        org.springframework.web.client: DEBUG
culqi:
    url:
        mod_pago: https://integ-pago.culqi.com
        mod_pago_integ: https://integ-pago.culqi.com
        mod_pago_cargos: https://integ-pago.culqi.com/api/v1/cargos
        mod_suscripciones: https://integ-pago.culqi.com/ejemplo-suscripcion
    config:
        codigoComercio: test_FpSiSoyFpGzG
        llaveSecreta: eLHsrNFGp0PCnHfSMmW4DmgcYrylYkOVqufX5apTiUg=

